services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    environment:
      - AVANZA_ACCOUNT_ID = ${AVANZA_ACCOUNT_ID}
      - AVANZA_TOTP_SECRET= ${AVANZA_TOTP_SECRET}
      - AVANZA_PASSWORD   = ${AVANZA_PASSWORD}
      - AVANZA_USERNAME   = ${AVANZA_USERNAME}
    volumes:
      - .:/app
