services:
  app:
    build: .
    environment:
      - AVANZA_ACCOUNT_ID=${AVANZA_ACCOUNT_ID}
      - AVANZA_TOTP_SECRET=${AVANZA_TOTP_SECRET}
      - AVANZA_PASSWORD=${AVANZA_PASSWORD}
      - AVANZA_USERNAME=${AVANZA_USERNAME}
    volumes:
      - .:/app
